name: On Change

# Runs all tests whenever a commit is pushed to a main branch.
on:
  push:
    branches: [ 'master', 'develop', 'release/**' ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  run-frontend-tests:
    uses: ./.github/workflows/frontend-tests.yml
    secrets: inherit
    timeout-minutes: 20

  run-backend-tests:
    uses: ./.github/workflows/backend-tests.yml
    secrets: inherit
    timeout-minutes: 75
